import type { Product, Review } from '@/types';

let skuSeq = 1000;
function sku(prefix: string): string {
  skuSeq += 7;
  return `${prefix}-${skuSeq}`;
}

function rev(id: number, name: string, rating: number, daysAgo: number, title: string, body: string): Review {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return {
    id: `r${id}`,
    name,
    rating,
    date: d.toISOString(),
    title,
    body,
  };
}

const SIZES_M = [39, 40, 41, 42, 43, 44, 45];
const SIZES_W = [35, 36, 37, 38, 39, 40, 41];
const SIZES_K = [28, 29, 30, 31, 32, 33, 34, 35];

const C = {
  black: { name: 'Black', hex: '#1a1a1a' },
  brown: { name: 'Brown', hex: '#6b4423' },
  tan: { name: 'Tan', hex: '#c19a6b' },
  white: { name: 'White', hex: '#f5f5f0' },
  navy: { name: 'Navy', hex: '#1e3a5f' },
  grey: { name: 'Grey', hex: '#8b8b8b' },
  red: { name: 'Red', hex: '#c0392b' },
  blue: { name: 'Blue', hex: '#2c5aa0' },
  beige: { name: 'Beige', hex: '#d9c4a3' },
  gold: { name: 'Gold', hex: '#d4af37' },
  olive: { name: 'Olive', hex: '#5b6230' },
  burgundy: { name: 'Burgundy', hex: '#5e1f2d' },
  pink: { name: 'Pink', hex: '#e8a0b8' },
  yellow: { name: 'Yellow', hex: '#f4c430' },
};

type Seed = Omit<Product, 'id' | 'sku' | 'reviews' | 'reviewCount' | 'rating'> & {
  rating?: number;
  reviews?: Review[];
};

const seeds: Seed[] = [
  // ---------------- MEN ----------------
  {
    name: 'Oxford Brogue Classic',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'formal',
    price: 14999, salePrice: 11299,
    image: 'https://images.pexels.com/photos/4161710/pexels-photo-4161710.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/4161710/pexels-photo-4161710.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/293404/pexels-photo-293404.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    sizes: SIZES_M, colors: [C.black, C.brown],
    stock: 24, badge: 'Bestseller', isBestSeller: true,
    description: 'A timeless full-grain leather Oxford with hand-burnished toe broguing. Goodyear-welted construction means it can be resoled for years of wear.',
    specs: [['Upper', 'Full-grain calf leather'], ['Sole', 'Leather with rubber heel tap'], ['Construction', 'Goodyear welt'], ['Lining', 'Soft kid leather'], ['Weight', '420 g (per shoe)'], ['Origin', 'Crafted in Pakistan']] as any,
    tags: ['leather', 'oxford', 'office', 'wedding'], isNew: false,
    rating: 4.8,
    reviews: [rev(1,'Bilal Ahmed',5,9,'Wedding-ready','Wore these to my nikah. Extremely comfortable after a short break-in and the finish is beautiful.'),rev(2,'Hamza Khan',4,22,'Solid build','Leather quality is genuine. Sized half down as recommended and fit perfectly.'),rev(3,'Usman Tariq',5,40,'Worth every rupee','Third pair from VÉRONA. These look better with age.')],
  },
  {
    name: 'Derby Cap-Toe Executive',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'formal',
    price: 13500, salePrice: 10100,
    image: 'https://images.pexels.com/photos/37465528/pexels-photo-37465528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/37465528/pexels-photo-37465528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8159364/pexels-photo-8159364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.black],
    stock: 18, isBestSeller: true,
    description: 'A sleek cap-toe Derby for the boardroom. Minimalist lines, padded insole, and a durable TPR outsole.',
    specs: [['Upper','Full-grain leather'],['Sole','TPR'],['Closure','Lace-up'],['Weight','390 g']] as any,
    tags:['derby','office','minimal'], rating:4.6, reviews:[rev(4,'Ahsan Raza',5,12,'Office staple','Daily wear for the office. Very comfortable.'),rev(5,'Farhan Malik',4,30,'Good but stiff','Needed a week to soften up. Now great.')],
  },
  {
    name: 'Loafers Slip-On Heritage',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'formal',
    price: 11999, salePrice: 8999,
    image: 'https://images.pexels.com/photos/10259873/pexels-photo-10259873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/10259873/pexels-photo-10259873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/38570115/pexels-photo-38570115.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.black, C.tan],
    stock: 31, badge:'Sale',
    description: 'Penny loafers with a moccasin-stitched toe and cushioned footbed. Slip-on ease meets heritage craft.',
    specs:[['Upper','Leather'],['Sole','Rubber'],['Type','Slip-on'],['Weight','360 g']] as any, tags:['loafer','slip-on','smart-casual'], rating:4.7, reviews:[rev(6,'Saad Iqbal',5,7,'My go-to','So easy to wear. Goes with everything.')],
  },
  {
    name: 'Monk Strap Single Buckle',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'formal',
    price: 16500,
    image: 'https://images.pexels.com/photos/293404/pexels-photo-293404.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/293404/pexels-photo-293404.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/296159/pexels-photo-296159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.brown, C.burgundy],
    stock: 12, badge:'New', isNew:true,
    description: 'A single-buckle monk strap with antiqued leather and a hand-painted patina. For the man who knows his style.',
    specs:[['Upper','Antiqued leather'],['Closure','Single monk buckle'],['Sole','Leather'],['Weight','430 g']] as any, tags:['monk','statement','wedding'], rating:4.9, reviews:[rev(7,'Daniyal Sheikh',5,3,'Showstopper','Got compliments all evening at a wedding.')],
  },
  {
    name: 'Chelsea Boot Leather',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'boots',
    price: 17999, salePrice: 13999,
    image: 'https://images.pexels.com/photos/8159427/pexels-photo-8159427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8159427/pexels-photo-8159427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8159478/pexels-photo-8159478.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.brown, C.black],
    stock: 16,
    description: 'Ankle-high Chelsea boots with elastic side gussets and a low stacked heel. Refined enough for suiting, rugged enough for winter.',
    specs:[['Upper','Leather'],['Closure','Slip-on elastic'],['Heel','Stacked leather'],['Height','Ankle']] as any, tags:['boot','chelsea','winter'], rating:4.7, reviews:[rev(8,'Zain Abbas',5,15,'Perfect for winter','Warm, stylish and well made.')],
  },
  {
    name: 'Brogue Wingtip Tan',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'formal',
    price: 15500, salePrice: 11999,
    image: 'https://images.pexels.com/photos/26587838/pexels-photo-26587838.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/26587838/pexels-photo-26587838.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/13611901/pexels-photo-13611901.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.tan, C.brown],
    stock: 20, isBestSeller:true,
    description: 'Wingtip brogues with a decorative perforated toe pattern. A heritage design with a characterful tan finish.',
    specs:[['Upper','Full-grain leather'],['Pattern','Wingtip brogue'],['Sole','Leather'],['Construction','Goodyear welt']] as any, tags:['brogue','wingtip','tan'], rating:4.6, reviews:[rev(9,'Omar Farooq',4,18,'Beautiful patina','Looks better every month.')],
  },
  // Men sneakers
  {
    name: 'Urban Runner Low-Top',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sneakers',
    price: 9999, salePrice: 7499,
    image: 'https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.white, C.grey, C.black],
    stock: 42, badge:'Bestseller', isBestSeller:true,
    description: 'Everyday low-tops with a memory-foam insole and breathable knit upper. Light as air, built for the city.',
    specs:[['Upper','Engineered knit'],['Sole','EVA foam'],['Insole','Memory foam'],['Weight','280 g']] as any, tags:['sneaker','casual','everyday'], rating:4.5, reviews:[rev(10,'Ali Raza',5,5,'Daily driver','Most comfortable sneakers I own.'),rev(11,'Bilal',4,14,'Nice but runs small','Go half size up.')],
  },
  {
    name: 'StreetStyle High-Top',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sneakers',
    price: 10999,
    image: 'https://images.pexels.com/photos/30128844/pexels-photo-30128844.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/30128844/pexels-photo-30128844.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.black, C.white],
    stock: 26, badge:'New', isNew:true,
    description: 'High-top street sneakers with a padded collar and vulcanized rubber sole. Bold silhouette, all-day comfort.',
    specs:[['Upper','Canvas & synthetic'],['Sole','Vulcanized rubber'],['Collar','Padded'],['Closure','Lace-up']] as any, tags:['high-top','street'], rating:4.4, reviews:[rev(12,'Hassan',4,8,'Solid build','Great for winter.')],
  },
  {
    name: 'Minimalist White Trainer',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sneakers',
    price: 8999, salePrice: 6999,
    image: 'https://images.pexels.com/photos/12628400/pexels-photo-12628400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12628400/pexels-photo-12628400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/30707531/pexels-photo-30707531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.white],
    stock: 50, isBestSeller:true,
    description: 'Clean white leather trainers that go with everything. Cushioned heel cup and a flexible cup sole.',
    specs:[['Upper','Leather'],['Sole','Cup sole'],['Lining','Textile'],['Weight','320 g']] as any, tags:['minimal','white','leather'], rating:4.7, reviews:[rev(13,'Sufyan',5,6,'Goes with everything','My wardrobe essential now.')],
  },
  {
    name: 'Retro Court Sneaker',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sneakers',
    price: 9500, salePrice: 7200,
    image: 'https://images.pexels.com/photos/8979071/pexels-photo-8979071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8979071/pexels-photo-8979071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.white, C.blue, C.red],
    stock: 33, badge:'Sale',
    description: 'Retro-inspired court sneakers with a terrycloth tongue and contrast accents. A nod to 80s tennis style.',
    specs:[['Upper','Leather & textile'],['Sole','Rubber'],['Tongue','Terrycloth']] as any, tags:['retro','court','colorful'], rating:4.3, reviews:[rev(14,'Adeel',4,20,'Retro vibes','Love the look.')],
  },
  // Men sports
  {
    name: 'Marathon Pro Runner',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sports',
    price: 12999, salePrice: 9999,
    image: 'https://images.pexels.com/photos/12659352/pexels-photo-12659352.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12659352/pexels-photo-12659352.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/260044/pexels-photo-260044.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.blue, C.grey, C.black],
    stock: 38, badge:'Bestseller', isBestSeller:true,
    description: 'Cushioned road runners with a responsive foam midsole and breathable mesh. Built for daily mileage.',
    specs:[['Upper','Engineered mesh'],['Midsole','Responsive EVA'],['Outsole','Carbon rubber'],['Drop','8 mm']] as any, tags:['running','marathon','road'], rating:4.6, reviews:[rev(15,'Runner PK',5,4,'Great for daily runs','Cushioning is superb.'),rev(16,'Tariq',4,16,'Good grip','Holds up on wet roads.')],
  },
  {
    name: 'CrossFit Trainer Flex',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sports',
    price: 11500,
    image: 'https://images.pexels.com/photos/23491456/pexels-photo-23491456.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/23491456/pexels-photo-23491456.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.white, C.black],
    stock: 22, badge:'New', isNew:true,
    description: 'Versatile training shoes with a stable flat sole for lifting and a flexible forefoot for box jumps.',
    specs:[['Upper','Mesh & synthetic'],['Sole','Flat stable rubber'],['Use','Cross-training'],['Weight','340 g']] as any, tags:['gym','training','crossfit'], rating:4.5, reviews:[rev(17,'Gym Guy',5,9,'Solid for lifting','Flat base is great for squats.')],
  },
  {
    name: 'Trail Conqueror GTX',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sports',
    price: 14500, salePrice: 11800,
    image: 'https://images.pexels.com/photos/4065509/pexels-photo-4065509.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/4065509/pexels-photo-4065509.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.olive, C.black],
    stock: 17,
    description: 'Trail runners with aggressive lugs, a protective toe cap and water-resistant upper. Made for the northern trails.',
    specs:[['Upper','Water-resistant mesh'],['Outsole','5mm lugs'],['Toe','Rubber cap'],['Use','Trail running']] as any, tags:['trail','hiking','outdoor'], rating:4.7, reviews:[rev(18,'Hiker',5,11,'Survived Nathia Gali','Grip is incredible on rocks.')],
  },
  {
    name: 'Indoor Court Classic',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sports',
    price: 10500, salePrice: 8200,
    image: 'https://images.pexels.com/photos/14212621/pexels-photo-14212621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/14212621/pexels-photo-14212621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.white, C.blue],
    stock: 29,
    description: 'Non-marking indoor court shoes for badminton and squash. Gum rubber outsole for gym-floor grip.',
    specs:[['Upper','Synthetic leather'],['Outsole','Non-marking gum'],['Use','Indoor court'],['Weight','300 g']] as any, tags:['badminton','squash','court'], rating:4.4, reviews:[rev(19,'Player',4,13,'Good grip','Great for indoor games.')],
  },
  // Men casual
  {
    name: 'Canvas Slip-On Easy',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'casual',
    price: 5500, salePrice: 4200,
    image: 'https://images.pexels.com/photos/4271694/pexels-photo-4271694.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/4271694/pexels-photo-4271694.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.black, C.grey, C.navy],
    stock: 60, badge:'Sale',
    description: 'Lightweight canvas slip-ons with a foldable heel for shoe-horn wear. Weekend comfort in seconds.',
    specs:[['Upper','Canvas'],['Sole','Molded EVA'],['Closure','Slip-on'],['Weight','240 g']] as any, tags:['canvas','casual','slip-on'], rating:4.2, reviews:[rev(20,'Casual',4,25,'Comfy','Nice for errands.')],
  },
  {
    name: 'Suede Driving Moccasin',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'casual',
    price: 8999,
    image: 'https://images.pexels.com/photos/8159478/pexels-photo-8159478.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8159478/pexels-photo-8159478.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.tan, C.navy],
    stock: 21,
    description: 'Pebble-sole driving mocs in soft suede. Flexible, glove-like feel for long drives and relaxed days.',
    specs:[['Upper','Suede'],['Sole','Pebble rubber'],['Type','Driving loafer']] as any, tags:['driving','suede','moccasin'], rating:4.5, reviews:[rev(21,'Driver',5,17,'Long drive comfort','No more foot fatigue.')],
  },

  // ---------------- WOMEN ----------------
  {
    name: 'Stiletto Pointed Heel',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 12500, salePrice: 9400,
    image: 'https://images.pexels.com/photos/27204295/pexels-photo-27204295.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/27204295/pexels-photo-27204295.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/5398968/pexels-photo-5398968.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.beige, C.red],
    stock: 27, badge:'Bestseller', isBestSeller:true,
    description: 'A 9cm pointed-toe stiletto with a padded footbed and a sleek silhouette. Evening elegance, dialed in.',
    specs:[['Upper','Synthetic patent'],['Heel','9 cm stiletto'],['Footbed','Padded'],['Closure','Slip-on']] as any, tags:['heels','stiletto','party'], rating:4.6, reviews:[rev(22,'Ayesha',5,6,'Gorgeous','Wore to a wedding. So elegant.')],
  },
  {
    name: 'Block Heel Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 8999, salePrice: 6800,
    image: 'https://images.pexels.com/photos/27046154/pexels-photo-27046154.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/27046154/pexels-photo-27046154.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.white, C.beige],
    stock: 34,
    description: 'A comfortable 5cm block heel sandal with an ankle strap. Stable, walkable, and effortlessly chic.',
    specs:[['Upper','Leather'],['Heel','5 cm block'],['Strap','Adjustable ankle'],['Sole','Rubber']] as any, tags:['sandals','block-heel','summer'], rating:4.7, reviews:[rev(23,'Mariam',5,8,'All day comfort','Walked all evening, no pain.')],
  },
  {
    name: 'Gold Embellished Heels',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 13999,
    image: 'https://images.pexels.com/photos/12687623/pexels-photo-12687623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12687623/pexels-photo-12687623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/38708847/pexels-photo-38708847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.gold, C.black],
    stock: 14, badge:'New', isNew:true,
    description: 'Embellished gold heels with a delicate ankle strap and shimmer finish. Bridal and festive ready.',
    specs:[['Upper','Embellished metallic'],['Heel','8 cm'],['Detail','Crystal embellishment']] as any, tags:['bridal','festive','gold'], rating:4.9, reviews:[rev(24,'Bride',5,2,'Perfect for my mehndi','Sparkled all night.')],
  },
  {
    name: 'Kitten Heel Office',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 9500, salePrice: 7100,
    image: 'https://images.pexels.com/photos/12112063/pexels-photo-12112063.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12112063/pexels-photo-12112063.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/12112062/pexels-photo-12112062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.beige],
    stock: 23, badge:'Sale',
    description: 'A modest 4cm kitten heel with a pointed toe. Professional polish you can wear all day.',
    specs:[['Heel','4 cm kitten'],['Upper','Leather'],['Toe','Pointed']] as any, tags:['office','kitten-heel'], rating:4.5, reviews:[rev(25,'Office Goer',4,19,'Office perfect','Discreet and comfy.')],
  },
  {
    name: 'Buckle Strap Heels',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 11000, salePrice: 8499,
    image: 'https://images.pexels.com/photos/17826424/pexels-photo-17826424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/17826424/pexels-photo-17826424.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black],
    stock: 19,
    description: 'Statement heels with chain-detail buckle straps. A bold finish for evenings out.',
    specs:[['Heel','8 cm'],['Detail','Chain buckle'],['Upper','Leather']] as any, tags:['heels','statement','evening'], rating:4.4, reviews:[rev(26,'Sana',4,14,'Chic','Looks expensive.')],
  },
  {
    name: 'Strappy Summer Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 6500, salePrice: 4999,
    image: 'https://images.pexels.com/photos/10827097/pexels-photo-10827097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/10827097/pexels-photo-10827097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.beige],
    stock: 41, badge:'Sale',
    description: 'Breathable strappy sandals with a low heel and cushioned footbed. Summer days, sorted.',
    specs:[['Upper','Synthetic'],['Heel','2 cm'],['Footbed','Cushioned']] as any, tags:['sandals','summer','flats'], rating:4.3, reviews:[rev(27,'Summer',4,22,'Cute and comfy','Great for daily wear.')],
  },
  {
    name: 'Rhinestone Flat Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 7800,
    image: 'https://images.pexels.com/photos/35759100/pexels-photo-35759100.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/35759100/pexels-photo-35759100.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.gold, C.beige],
    stock: 18, badge:'New', isNew:true,
    description: 'Flat sandals with delicate rhinestone straps. A touch of sparkle for everyday elegance.',
    specs:[['Upper','Embellished'],['Heel','Flat'],['Detail','Rhinestones']] as any, tags:['flats','sparkle','sandals'], rating:4.6, reviews:[rev(28,'Elegant',5,5,'So pretty','Subtle sparkle, comfy.')],
  },
  {
    name: 'Leather Strap Heel Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 10200, salePrice: 7800,
    image: 'https://images.pexels.com/photos/36581188/pexels-photo-36581188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/36581188/pexels-photo-36581188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.brown, C.black],
    stock: 25,
    description: 'A sophisticated heeled sandal with leather cross-straps and an adjustable ankle buckle.',
    specs:[['Upper','Leather'],['Heel','6 cm'],['Strap','Ankle buckle']] as any, tags:['sandals','heels','leather'], rating:4.5, reviews:[rev(29,'Nida',4,12,'Well made','Leather is soft.')],
  },
  {
    name: 'Pointed Ballet Flat',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'casual',
    price: 6000, salePrice: 4500,
    image: 'https://images.pexels.com/photos/29761843/pexels-photo-29761843.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/29761843/pexels-photo-29761843.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige, C.pink, C.black],
    stock: 47, badge:'Sale', isBestSeller:true,
    description: 'Pointed-toe ballet flats with a bow detail and soft suede upper. Effortless feminine comfort.',
    specs:[['Upper','Suede'],['Sole','Flexible rubber'],['Detail','Bow'],['Heel','Flat']] as any, tags:['flats','ballet','casual'], rating:4.6, reviews:[rev(30,'Hira',5,7,'My favorite flats','Bought in 3 colors.')],
  },
  {
    name: 'Slide Sandal Comfort',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'casual',
    price: 4500, salePrice: 3400,
    image: 'https://images.pexels.com/photos/26954369/pexels-photo-26954369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/26954369/pexels-photo-26954369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige, C.pink, C.black],
    stock: 52,
    description: 'Cushioned slide sandals with a wide strap. Slip-on ease with all-day comfort.',
    specs:[['Upper','Synthetic'],['Footbed','Memory foam'],['Type','Slide'],['Heel','Flat']] as any, tags:['slides','casual','comfort'], rating:4.2, reviews:[rev(31,'Comfy',4,24,'House shoes','Good for home and quick outings.')],
  },
  {
    name: 'Leather Buckle Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 7200, salePrice: 5400,
    image: 'https://images.pexels.com/photos/31129841/pexels-photo-31129841.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/31129841/pexels-photo-31129841.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.brown],
    stock: 30,
    description: 'Minimalist leather sandals with adjustable buckle straps. A versatile warm-weather staple.',
    specs:[['Upper','Leather'],['Closure','Buckle'],['Sole','Rubber'],['Heel','2 cm']] as any, tags:['sandals','leather','minimal'], rating:4.4, reviews:[rev(32,'Minimal',4,16,'Clean look','Goes with everything.')],
  },
  {
    name: 'Open-Toe Mesh Heels',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 9800,
    image: 'https://images.pexels.com/photos/19889648/pexels-photo-19889648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/19889648/pexels-photo-19889648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black],
    stock: 16, badge:'New', isNew:true,
    description: 'Open-toe heels with a perforated mesh upper and sculpted heel. Modern, breathable, and striking.',
    specs:[['Upper','Mesh & leather'],['Heel','7 cm sculpted'],['Toe','Open']] as any, tags:['heels','open-toe','modern'], rating:4.5, reviews:[rev(33,'Trendy',5,4,'Unique look','Get compliments every time.')],
  },
  {
    name: 'Bridal White Flats',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 8500, salePrice: 6400,
    image: 'https://images.pexels.com/photos/29397475/pexels-photo-29397475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/29397475/pexels-photo-29397475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.white, C.beige],
    stock: 20,
    description: 'Delicate white flats with floral detailing for the bride who values comfort on her big day.',
    specs:[['Upper','Textile'],['Detail','Floral'],['Heel','Flat'],['Lining','Soft']] as any, tags:['bridal','flats','white'], rating:4.8, reviews:[rev(34,'Bride 2',5,1,'Wedding ready','Wore all day, no blisters.')],
  },
  // Women sneakers
  {
    name: 'Women Knit Sneaker',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sneakers',
    price: 7800, salePrice: 5900,
    image: 'https://images.pexels.com/photos/11324518/pexels-photo-11324518.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/11324518/pexels-photo-11324518.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.white, C.pink, C.grey],
    stock: 44, badge:'Bestseller', isBestSeller:true,
    description: 'Sock-fit knit sneakers with a springy midsole. Lightweight, breathable, and ready for anything.',
    specs:[['Upper','Knit'],['Sole','Spring EVA'],['Fit','Sock-fit'],['Weight','240 g']] as any, tags:['sneaker','knit','women'], rating:4.5, reviews:[rev(35,'Ayesha',5,9,'So light','Feels like walking on clouds.')],
  },
  {
    name: 'Women Sport Runner',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sports',
    price: 9500, salePrice: 7200,
    image: 'https://images.pexels.com/photos/7880182/pexels-photo-7880182.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/7880182/pexels-photo-7880182.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8456072/pexels-photo-8456072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.grey, C.pink, C.white],
    stock: 36, badge:'Sale',
    description: 'Cushioned running shoes designed for a woman\'s stride. Stable heel, breathable mesh, reflective accents.',
    specs:[['Upper','Mesh'],['Midsole','Cushioned EVA'],['Heel','Stable cradle'],['Use','Running']] as any, tags:['running','women','sport'], rating:4.6, reviews:[rev(36,'Runner W',5,6,'Great support','My knees thank me.')],
  },
  {
    name: 'Platform White Sneaker',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sneakers',
    price: 8200,
    image: 'https://images.pexels.com/photos/11324548/pexels-photo-11324548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/11324548/pexels-photo-11324548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.white, C.pink],
    stock: 28, badge:'New', isNew:true,
    description: 'Platform sneakers with a chunky 4cm sole and clean leather upper. A little height, a lot of style.',
    specs:[['Upper','Leather'],['Sole','Platform 4 cm'],['Weight','320 g']] as any, tags:['platform','sneaker','women'], rating:4.4, reviews:[rev(37,'Style',4,10,'Cute height','Love the lift.')],
  },
  {
    name: 'Women Walking Shoe',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sports',
    price: 8800, salePrice: 6600,
    image: 'https://images.pexels.com/photos/8454904/pexels-photo-8454904.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8454904/pexels-photo-8454904.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.grey, C.white],
    stock: 32,
    description: 'Lightweight walking shoes with arch support and a flexible sole. Built for long walks and daily errands.',
    specs:[['Upper','Mesh'],['Arch','Supportive'],['Sole','Flexible EVA'],['Use','Walking']] as any, tags:['walking','comfort','women'], rating:4.5, reviews:[rev(38,'Walker',4,15,'All day comfort','Great for my daily walks.')],
  },
  {
    name: 'Yoga Studio Slip-On',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sports',
    price: 6500, salePrice: 4900,
    image: 'https://images.pexels.com/photos/27174535/pexels-photo-27174535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/27174535/pexels-photo-27174535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige, C.pink],
    stock: 38, badge:'Sale',
    description: 'Flexible studio slip-ons with a split sole for yoga, pilates, and studio classes. Barely-there feel.',
    specs:[['Upper','Stretch knit'],['Sole','Split sole'],['Use','Yoga / studio'],['Weight','180 g']] as any, tags:['yoga','studio','lightweight'], rating:4.3, reviews:[rev(39,'Yogi',4,18,'Studio perfect','Great grip on the mat.')],
  },
  {
    name: 'Red Statement Sneaker',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sneakers',
    price: 9200,
    image: 'https://images.pexels.com/photos/31688982/pexels-photo-31688982.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/31688982/pexels-photo-31688982.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/31688978/pexels-photo-31688978.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.red, C.white],
    stock: 22, isBestSeller:true,
    description: 'Bold red sneakers with white accents. A pop of color that elevates any casual outfit.',
    specs:[['Upper','Leather'],['Sole','Rubber'],['Detail','Contrast accents']] as any, tags:['sneaker','red','statement'], rating:4.6, reviews:[rev(40,'Bold',5,3,'Eye-catching','Everyone asks where I got them.')],
  },
  {
    name: 'Beaded Block Heel',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 10700, salePrice: 8100,
    image: 'https://images.pexels.com/photos/27023941/pexels-photo-27023941.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/27023941/pexels-photo-27023941.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.blue, C.black],
    stock: 15,
    description: 'Embellished block-heel sandals with delicate buckle detailing. Elegant and stable for long evenings.',
    specs:[['Heel','6 cm block'],['Upper','Embellished'],['Closure','Buckle']] as any, tags:['heels','embellished','evening'], rating:4.7, reviews:[rev(41,'Elegant 2',5,6,'Festive ready','Wore to a mayun. Loved them.')],
  },
  {
    name: 'Nude Pointed Pump',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 9700, salePrice: 7300,
    image: 'https://images.pexels.com/photos/32496673/pexels-photo-32496673.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/32496673/pexels-photo-32496673.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige],
    stock: 26, badge:'Sale',
    description: 'A versatile nude pump with a textured finish and 7cm heel. Lengthens the leg, pairs with everything.',
    specs:[['Heel','7 cm'],['Upper','Textured'],['Toe','Pointed']] as any, tags:['pump','nude','office'], rating:4.5, reviews:[rev(42,'Classic',4,11,'Wardrobe staple','So versatile.')],
  },

  // ---------------- KIDS ----------------
  {
    name: 'Kids Court Sneaker',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sneakers',
    price: 4500, salePrice: 3399,
    image: 'https://images.pexels.com/photos/30395128/pexels-photo-30395128.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/30395128/pexels-photo-30395128.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.red, C.white, C.blue],
    stock: 48, badge:'Bestseller', isBestSeller:true,
    description: 'Durable court sneakers for active kids. Easy hook-and-loop closure and a scuff-resistant toe.',
    specs:[['Upper','Leather & textile'],['Closure','Hook-and-loop'],['Toe','Scuff guard'],['Use','Everyday']] as any, tags:['kids','sneaker','velcro'], rating:4.7, reviews:[rev(43,'Parent',5,8,'Easy for school','Kid puts them on alone now.')],
  },
  {
    name: 'Kids School Shoes',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'formal',
    price: 3800, salePrice: 2900,
    image: 'https://images.pexels.com/photos/29737094/pexels-photo-29737094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/29737094/pexels-photo-29737094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.black],
    stock: 55, badge:'Sale', isBestSeller:true,
    description: 'Polished black school shoes with a sturdy sole and easy lace or velcro option. Uniform-ready.',
    specs:[['Upper','Polished leather'],['Sole','Durable rubber'],['Closure','Lace / velcro'],['Use','School']] as any, tags:['school','kids','uniform'], rating:4.6, reviews:[rev(44,'Mom',5,13,'Survives the playground','Held up all term.')],
  },
  {
    name: 'Kids Running Shoes',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sports',
    price: 5200, salePrice: 3999,
    image: 'https://images.pexels.com/photos/9537104/pexels-photo-9537104.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/9537104/pexels-photo-9537104.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.grey, C.blue, C.red],
    stock: 40, badge:'Sale',
    description: 'Cushioned running shoes for kids with a breathable mesh upper and bouncy foam. Built for the playground.',
    specs:[['Upper','Mesh'],['Sole','Cushioned EVA'],['Closure','Elastic lace + velcro'],['Use','Sports']] as any, tags:['kids','running','sports'], rating:4.5, reviews:[rev(45,'Active kid',4,14,'Bouncy','My son loves them.')],
  },
  {
    name: 'Kids Canvas Slip-On',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'casual',
    price: 3200, salePrice: 2400,
    image: 'https://images.pexels.com/photos/2271522/pexels-photo-2271522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/2271522/pexels-photo-2271522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.red, C.yellow, C.blue],
    stock: 60, badge:'Sale',
    description: 'Playful canvas slip-ons with elastic panels so kids can pull them on themselves. Fun colors, easy mornings.',
    specs:[['Upper','Canvas'],['Sole','Flexible rubber'],['Closure','Slip-on']] as any, tags:['kids','canvas','slip-on'], rating:4.4, reviews:[rev(46,'Dad',4,19,'Easy mornings','No more tying laces.')],
  },
  {
    name: 'Kids Baby Booties',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'casual',
    price: 2500,
    image: 'https://images.pexels.com/photos/13822967/pexels-photo-13822967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/13822967/pexels-photo-13822967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/15668369/pexels-photo-15668369.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: [20, 22, 24, 26], colors: [C.brown, C.beige],
    stock: 35, badge:'New', isNew:true,
    description: 'Soft leather baby booties with gentle ankle support and a flexible sole for first walkers.',
    specs:[['Upper','Soft leather'],['Sole','Flexible'],['Use','First walkers'],['Age','6-24 months']] as any, tags:['baby','first-walkers','soft'], rating:4.9, reviews:[rev(47,'New mom',5,2,'Adorable','Perfect for my baby\'s first steps.')],
  },
  {
    name: 'Kids Light-Up Sneaker',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sneakers',
    price: 4900, salePrice: 3700,
    image: 'https://images.pexels.com/photos/7207554/pexels-photo-7207554.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/7207554/pexels-photo-7207554.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.red, C.blue, C.pink],
    stock: 33, badge:'New', isNew:true,
    description: 'Sneakers that light up with every step. USB-rechargeable LED sole and a cushioned insole for all-day play.',
    specs:[['Upper','Synthetic'],['Sole','LED (USB recharge)'],['Closure','Velcro'],['Use','Play']] as any, tags:['kids','light-up','fun'], rating:4.6, reviews:[rev(48,'Kid approved',5,4,'Best gift ever','My daughter won\'t take them off.')],
  },
  {
    name: 'Kids Sandals Summer',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sandals',
    price: 2800, salePrice: 2100,
    image: 'https://images.pexels.com/photos/38817213/pexels-photo-38817213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/38817213/pexels-photo-38817213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.red, C.blue],
    stock: 42, badge:'Sale',
    description: 'Breathable summer sandals with adjustable straps and a grippy sole. Beach, park, and playground ready.',
    specs:[['Upper','Synthetic'],['Sole','Grippy rubber'],['Closure','Velcro straps'],['Use','Summer']] as any, tags:['kids','sandals','summer'], rating:4.3, reviews:[rev(49,'Summer mom',4,16,'Good for the beach','Quick to dry.')],
  },
  {
    name: 'Kids Leather Party Shoes',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'formal',
    price: 4200, salePrice: 3150,
    image: 'https://images.pexels.com/photos/14447083/pexels-photo-14447083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/14447083/pexels-photo-14447083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.black, C.brown],
    stock: 24,
    description: 'Smart leather party shoes with a classic brogue detail. For Eid photos, weddings, and special occasions.',
    specs:[['Upper','Leather'],['Detail','Brogue'],['Sole','Leather'],['Use','Party']] as any, tags:['kids','party','eid'], rating:4.5, reviews:[rev(50,'Eid ready',5,5,'Perfect for Eid','Looked so smart.')],
  },
  {
    name: 'Kids Hiking Shoes',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sports',
    price: 5800,
    image: 'https://images.pexels.com/photos/18745880/pexels-photo-18745880.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/18745880/pexels-photo-18745880.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.red, C.olive],
    stock: 18, badge:'New', isNew:true,
    description: 'Rugged kids hiking shoes with ankle support, a protective toe cap, and grippy lugs for the trail.',
    specs:[['Upper','Synthetic & mesh'],['Ankle','Padded support'],['Toe','Rubber cap'],['Use','Hiking']] as any, tags:['kids','hiking','outdoor'], rating:4.7, reviews:[rev(51,'Hiker dad',5,7,'Trail ready','Took my son to Mushkpuri, no slips.')],
  },
  {
    name: 'Kids Soft-Soled Prewalker',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'casual',
    price: 2200, salePrice: 1650,
    image: 'https://images.pexels.com/photos/35753260/pexels-photo-35753260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/35753260/pexels-photo-35753260.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: [18, 19, 20, 21], colors: [C.yellow, C.pink],
    stock: 30, badge:'Sale',
    description: 'Ultra-soft prewalker shoes with a non-slip suede sole. Gentle on tiny growing feet.',
    specs:[['Upper','Soft textile'],['Sole','Suede non-slip'],['Age','3-12 months'],['Use','Prewalker']] as any, tags:['baby','prewalker','soft'], rating:4.8, reviews:[rev(52,'New parent',5,3,'So soft','Perfect for my baby.')],
  },

  // ---------------- EXTRA MEN ----------------
  {
    name: 'Chukka Boot Suede',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'boots',
    price: 13500, salePrice: 10200,
    image: 'https://images.pexels.com/photos/12210275/pexels-photo-12210275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12210275/pexels-photo-12210275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.brown, C.tan],
    stock: 20,
    description: 'Two-eyelet chukka boots in soft suede with a crepe-style sole. Smart-casual versatility at its best.',
    specs:[['Upper','Suede'],['Closure','Two-eyelet lace'],['Sole','Crepe rubber'],['Height','Ankle']] as any, tags:['chukka','suede','smart-casual'], rating:4.6, reviews:[rev(53,'Stylish',5,12,'Versatile','Wear with jeans or trousers.')],
  },
  {
    name: 'Leather Sandal Open',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'sandals',
    price: 5800, salePrice: 4400,
    image: 'https://images.pexels.com/photos/18735061/pexels-photo-18735061.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/18735061/pexels-photo-18735061.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.brown, C.black],
    stock: 37, badge:'Sale',
    description: 'Open leather sandals with adjustable straps and a contoured footbed. Summer comfort for men.',
    specs:[['Upper','Leather'],['Sole','Contoured rubber'],['Closure','Velcro'],['Use','Summer']] as any, tags:['men','sandals','summer'], rating:4.2, reviews:[rev(54,'Summer dad',4,20,'Cool in summer','Good for hot days.')],
  },
  {
    name: 'Men Sport Sandal',
    brand: 'VÉRONA Sport',
    gender: 'men', category: 'sandals',
    price: 6200, salePrice: 4700,
    image: 'https://images.pexels.com/photos/9267585/pexels-photo-9267585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/9267585/pexels-photo-9267585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.blue, C.black],
    stock: 29,
    description: 'Sport sandals with cushioned straps and a grippy outsole. From river crossings to city strolls.',
    specs:[['Upper','Synthetic'],['Sole','Grippy rubber'],['Closure','Buckle & velcro'],['Use','Outdoor / water']] as any, tags:['sport-sandal','outdoor','men'], rating:4.3, reviews:[rev(55,'Trekker',4,13,'Good grip','Used on a river trek. Held up well.')],
  },
  {
    name: 'Classic Penny Loafer',
    brand: 'VÉRONA Atelier',
    gender: 'men', category: 'casual',
    price: 9800, salePrice: 7400,
    image: 'https://images.pexels.com/photos/8159364/pexels-photo-8159364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8159364/pexels-photo-8159364.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_M, colors: [C.black, C.burgundy],
    stock: 23,
    description: 'A polished penny loafer that bridges formal and casual. Cushioned footbed and a flexible sole.',
    specs:[['Upper','Leather'],['Detail','Penny strap'],['Sole','Rubber'],['Type','Slip-on']] as any, tags:['loafer','penny','smart-casual'], rating:4.5, reviews:[rev(56,'Classic',4,17,'Sharp','Looks great with chinos.')],
  },

  // ---------------- EXTRA WOMEN ----------------
  {
    name: 'Women Ankle Bootie',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'boots',
    price: 11500, salePrice: 8700,
    image: 'https://images.pexels.com/photos/15065463/pexels-photo-15065463.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/15065463/pexels-photo-15065463.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.black, C.brown],
    stock: 17, badge:'New', isNew:true,
    description: 'Sleek ankle booties with a stacked block heel and side zip. Winter elegance with all-day stability.',
    specs:[['Upper','Leather'],['Heel','6 cm block'],['Closure','Side zip'],['Height','Ankle']] as any, tags:['boots','ankle','winter'], rating:4.7, reviews:[rev(57,'Boot lover',5,4,'Winter staple','So chic with jeans.')],
  },
  {
    name: 'Women Espadrille Flat',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'casual',
    price: 5200, salePrice: 3900,
    image: 'https://images.pexels.com/photos/14447345/pexels-photo-14447345.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/14447345/pexels-photo-14447345.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.red, C.beige],
    stock: 39, badge:'Sale',
    description: 'Classic espadrille flats with a jute wedge sole. Light, breezy, and perfect for summer.',
    specs:[['Upper','Canvas'],['Sole','Jute wedge'],['Heel','3 cm'],['Use','Summer']] as any, tags:['espadrille','summer','flat'], rating:4.4, reviews:[rev(58,'Summer girl',4,15,'Cute for summer','Light and comfy.')],
  },
  {
    name: 'Women Hiking Boot',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'boots',
    price: 12500, salePrice: 9500,
    image: 'https://images.pexels.com/photos/33172446/pexels-photo-33172446.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/33172446/pexels-photo-33172446.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.grey, C.olive],
    stock: 14,
    description: 'Lightweight hiking boots with waterproof membrane and aggressive grip. Made for the mountains.',
    specs:[['Upper','Waterproof'],['Sole','5mm lugs'],['Ankle','Supportive'],['Use','Hiking']] as any, tags:['hiking','boots','outdoor','women'], rating:4.8, reviews:[rev(59,'Trekker W',5,6,'Hunza ready','Did Fairy Meadows in these. Amazing grip.')],
  },
  {
    name: 'Wedge Heel Sandal',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'sandals',
    price: 7600, salePrice: 5700,
    image: 'https://images.pexels.com/photos/27174535/pexels-photo-27174535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/27174535/pexels-photo-27174535.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige, C.pink],
    stock: 27, badge:'Sale',
    description: 'Wedge heel sandals with a platform sole and ankle strap. Height and comfort in one.',
    specs:[['Heel','7 cm wedge'],['Upper','Synthetic'],['Strap','Ankle'],['Sole','Platform']] as any, tags:['wedge','sandals','platform'], rating:4.3, reviews:[rev(60,'Wedge fan',4,14,'Comfy height','No pain even after hours.')],
  },
  {
    name: 'Women Trail Runner',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sports',
    price: 11000, salePrice: 8400,
    image: 'https://images.pexels.com/photos/8454917/pexels-photo-8454917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8454917/pexels-photo-8454917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.pink, C.grey],
    stock: 21,
    description: 'Trail runners for women with a protective toe cap, rock plate, and grippy lugs for off-road adventures.',
    specs:[['Upper','Mesh'],['Plate','Rock plate'],['Outsole','4mm lugs'],['Use','Trail']] as any, tags:['trail','running','women'], rating:4.6, reviews:[rev(61,'Trail W',5,8,'Confident on rocks','Great protection.')],
  },
  {
    name: 'Glitter Party Heels',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'formal',
    price: 12300, salePrice: 9200,
    image: 'https://images.pexels.com/photos/38708847/pexels-photo-38708847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/38708847/pexels-photo-38708847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.gold, C.black],
    stock: 13, badge:'New', isNew:true,
    description: 'Glittering party heels with a stiletto heel and ankle strap. Shine at every celebration.',
    specs:[['Upper','Glitter fabric'],['Heel','8 cm stiletto'],['Strap','Ankle buckle']] as any, tags:['party','glitter','heels'], rating:4.8, reviews:[rev(62,'Party',5,3,'Sparkle queen','So glamorous.')],
  },
  {
    name: 'Women Golf Spike',
    brand: 'VÉRONA Sport',
    gender: 'women', category: 'sports',
    price: 13500,
    image: 'https://images.pexels.com/photos/32145212/pexels-photo-32145212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/32145212/pexels-photo-32145212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.white, C.grey],
    stock: 11,
    description: 'Golf shoes with soft spikes for grip and a waterproof upper. Stability through every swing.',
    specs:[['Upper','Waterproof leather'],['Sole','Soft spikes'],['Use','Golf'],['Weight','300 g']] as any, tags:['golf','women','sport'], rating:4.5, reviews:[rev(63,'Golfer',4,9,'Stable swing','Good grip on the course.')],
  },
  {
    name: 'Women Comfort Mule',
    brand: 'VÉRONA Femme',
    gender: 'women', category: 'casual',
    price: 5800, salePrice: 4350,
    image: 'https://images.pexels.com/photos/8989536/pexels-photo-8989536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/8989536/pexels-photo-8989536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_W, colors: [C.beige, C.black],
    stock: 34, badge:'Sale',
    description: 'Backless mules with a cushioned footbed and soft leather upper. Slip-on comfort with a polished look.',
    specs:[['Upper','Leather'],['Sole','Cushioned'],['Type','Mule / backless'],['Heel','2 cm']] as any, tags:['mule','comfort','casual'], rating:4.4, reviews:[rev(64,'Comfy W',4,12,'Easy slip-on','Great for work from home days.')],
  },

  // ---------------- EXTRA KIDS ----------------
  {
    name: 'Kids Football Boots',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'sports',
    price: 6200, salePrice: 4700,
    image: 'https://images.pexels.com/photos/29342147/pexels-photo-29342147.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/29342147/pexels-photo-29342147.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.blue, C.red],
    stock: 26, badge:'Sale',
    description: 'Kids football boots with molded studs for firm ground. Lightweight upper for quick touches.',
    specs:[['Upper','Synthetic'],['Studs','Molded FG'],['Use','Football'],['Weight','240 g']] as any, tags:['kids','football','sport'], rating:4.6, reviews:[rev(65,'Football mom',5,7,'My son loves them','Great grip on grass.')],
  },
  {
    name: 'Kids Mary Jane',
    brand: 'VÉRONA Junior',
    gender: 'kids', category: 'formal',
    price: 3600, salePrice: 2700,
    image: 'https://images.pexels.com/photos/12112063/pexels-photo-12112063.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: ['https://images.pexels.com/photos/12112063/pexels-photo-12112063.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],
    sizes: SIZES_K, colors: [C.black, C.pink],
    stock: 31, badge:'Sale',
    description: 'Classic Mary Jane shoes with a single strap buckle. Sweet and smart for school and parties.',
    specs:[['Upper','Patent'],['Closure','Strap buckle'],['Sole','Rubber'],['Use','School / party']] as any, tags:['kids','mary-jane','party'], rating:4.5, reviews:[rev(66,'Mary Jane',4,18,'Adorable','My daughter loves the buckle.')],
  },
];

export const PRODUCTS: Product[] = seeds.map((s, i) => {
  const { rating, reviews, ...rest } = s;
  const id = `p${(i + 1).toString().padStart(3, '0')}`;
  const reviewList = reviews ?? [];
  const avgRating = rating ?? (reviewList.length ? reviewList.reduce((a, r) => a + r.rating, 0) / reviewList.length : 4.5);
  return {
    ...rest,
    id,
    sku: sku('VRN'),
    rating: Math.round(avgRating * 10) / 10,
    reviews: reviewList,
    reviewCount: reviewList.length + Math.floor(Math.random() * 40) + 5,
    specs: (rest.specs as any).map((sp: [string, string]) => ({ label: sp[0], value: sp[1] })),
  } as Product;
});

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsByGender(gender: 'men' | 'women' | 'kids'): Product[] {
  return PRODUCTS.filter((p) => p.gender === gender);
}

export function productsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}
